### ISSUE TITLE
Set My TD stops working periodically.

### ISSUE THREAD

**Issue by toomanydemons** [mrven/Blender-Texel-Density-Checker#1]
I have been using this addon extensively for quite some time, even before 2.8. I do a lot of environment design.
In the latest release (2.0) there is a strange bug where "set my TD" stops working completely. I can rapid-fire the button like crazy and it just won't work at all. I can demonstrate this first-hand (TooManyDemons #2125 on Discord) and I'm not sure if this bug is only for me, or if others are having a similar issue. I've reverted for now to the older update. I love your tool quite a bit and felt I should mention it. Cheers!

**Comment by mrven** [comment]
I can't repeat this bug in any cases
