### ISSUE TITLE
as of blender 3.5.1 the addon is in the wrong N panel

### ISSUE THREAD

**Issue by manuelonthemic** [mrven/Blender-Texel-Density-Checker#14]
its appearing in the viewport n panel instead of the uv editor n panel
![image](https://github.com/mrven/Blender-Texel-Density-Checker/assets/33070823/cff23443-0213-4185-a7f0-97a799666edd)

**Comment by mrven** [comment]
Thanks for report! I will research this problem

**Comment by mrven** [comment]
This is not a bug. You are in object mode and operate with objects in current context, not directly with uv. Therefore Texel Density panel don't show in UV Editor. If you will switch to edit mode, then Texel Density panel will appear in UV Editor again.
