### ISSUE TITLE
Request: Publish as official "Comunity" Add-on?

### ISSUE THREAD

**Issue by jhm-ciberman** [mrven/Blender-Texel-Density-Checker#15]
Hello. I really don't know anything about blender development or blender comunity in general, but I find this Add-on extremely useful. 

**Request: Would it be possible to publish it as a "Comunity" add-on so it appears by default in the list of Comunity add-ons when you browse the "Add-ons" tab?**

![image](https://github.com/mrven/Blender-Texel-Density-Checker/assets/7988351/ea454313-7030-4215-a28d-5b436e553143)

Btw, this a character that I'm making using your great add-on. This addon let me ensure a 64px per unit consistency in my texel density. Thank you! 
![image](https://github.com/mrven/Blender-Texel-Density-Checker/assets/7988351/d51583c6-27ff-457c-86fe-e02ba68ccbb5)

**Comment by stilobique** [comment]
To be a Community plugin, follow these [instructions](https://wiki.blender.org/wiki/Process/Addons/Guidelines) :) .

**Comment by mrven** [comment]
see #28
