### ISSUE TITLE
UV Distortion Map in the viewport

### ISSUE THREAD

**Issue by xan2622** [mrven/Blender-Texel-Density-Checker#2]
Hi.

![48a9b5ac00a746ac8e4669445846179d-h](https://user-images.githubusercontent.com/1732773/79017121-dd71d580-7b70-11ea-8c8e-b1df2a7ec128.png)

Could **Texel Density Checker** have an option to display **UV distortion** not just in the UV Editor, but in the Viewport as a heatmap as well.

These _Right-Click-Select_ suggestions sum up this request quite well: 

Show UV Distortion in the Viewport as a heatmap: 
https://blender.community/c/rightclickselect/Zzfbbc/

Show UV distortion Heat Map in 3D View: 
https://blender.community/c/rightclickselect/7hdbbc/

**Comment by mrven** [comment]
Added in a future version 205cfa0

![Image](https://github.com/mrven/Blender-Texel-Density-Checker/assets/6444269/1b554333-29ad-49c9-9f15-aaa322b98b71)
