### ISSUE TITLE
Ability to remove panel from 3D Viewport

### ISSUE THREAD

**Issue by LalaGhost** [mrven/Blender-Texel-Density-Checker#23]
I have a lot of panels from add-ons in the 3D viewport and would like to minimize them.
When I empty the text field "Panel Category (3D View)" in the add-ons preferences the name of the panel will just be "Misc".
![Screenshot_4](https://github.com/mrven/Blender-Texel-Density-Checker/assets/43962138/93243077-0c8b-4c7f-a623-e9f2ee8b6eb0)

Is there a way to completely remove it from the 3D viewport but leave it in the UV editor?

**Comment by mrven** [comment]
Added in a future version 49a8604

![image](https://github.com/mrven/Blender-Texel-Density-Checker/assets/6444269/35e78027-3f39-4d24-b74e-5a608ab027f6)
