### ISSUE TITLE
get error blender 2.9

### ISSUE THREAD

**Issue by koloved** [mrven/Blender-Texel-Density-Checker#5]
i get error when i try SET my TD in this case
probably one of the objects has NO one UV
![Screenshot_5](https://user-images.githubusercontent.com/22406105/92951248-ba708800-f466-11ea-8b6a-b924433f5d39.jpg)
its hard to detect when you have many objects

BLEND file - [https://send.tresorit.com/a#H--tVFNk5EdAZq1UMq23bA](https://send.tresorit.com/a#H--tVFNk5EdAZq1UMq23bA)

**Comment by mrven** [comment]
Confirmed

**Comment by mrven** [comment]
Fixed in [v3.2.1](https://github.com/mrven/Blender-Texel-Density-Checker/releases/tag/v3.2.1)
