### ISSUE TITLE
error when attempting to set texel density in blender 2.91 beta

### ISSUE THREAD

**Issue by Rodg88** [mrven/Blender-Texel-Density-Checker#6]
In a new blend file with a cube or some other mesh, go to the uv editor, select the object in edit mode, select the UV map island, and try to press one of the 'Set TD' buttons, and I got the following error:

`Python: Traceback (most recent call last):
  File "D:\blender 2.91.0\2.91\scripts\addons\Texel_Density_3_2_1_283\add_td_operators.py", line 87, in execute
    bpy.ops.object.texel_density_set()
  File "D:\blender 2.91.0\2.91\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "D:\blender 2.91.0\2.91\scripts\addons\Texel_Density_3_2_1_283\core_td_operators.py", line 221, in execute
    bpy.context.screen.areas[ie_area].ui_type = 'VIEW'
TypeError: bpy_struct: item.attr = val: enum "VIEW" not found in ('VIEW_3D', 'IMAGE_EDITOR', 'UV', 'CompositorNodeTree', 'TextureNodeTree', 'ShaderNodeTree', 'SEQUENCE_EDITOR', 'CLIP_EDITOR', 'DOPESHEET', 'TIMELINE', 'FCURVES', 'DRIVERS', 'NLA_EDITOR', 'TEXT_EDITOR', 'CONSOLE', 'INFO', 'OUTLINER', 'PROPERTIES', 'FILE_BROWSER', 'PREFERENCES')

location: D:\blender 2.91.0\2.91\scripts\modules\bpy\ops.py:132

location: <unknown location>:-1

`

**Comment by mrven** [comment]
Fixed
