### ISSUE TITLE
Headless mode?

### ISSUE THREAD

**Issue by samevision** [mrven/Blender-Texel-Density-Checker#8]
Hi,

I really like this plugin. But I would love to implement it in my automation process. Setting the texel density in blender -b (background mode) is not working since this addon asks for:

`if bpy.context.area.spaces.active.type == "IMAGE_EDITOR" and bpy.context.scene.tool_settings.use_uv_select_sync == False`

bpy.context.area doesn't exists due to the lack of ui. Is it still possible somehow?

Best

**Comment by mrven** [comment]
Hi. Thanks! No, this not possible. Handless mode needs another archeticture of addon. TD uses many Blender functions, whivh works only with UI
